server:
  port: 8086
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://192.168.80.166:9200


