server:
  port: 8092
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.80.166
  rabbitmq:
    host: 192.168.80.166
    username: user
    password: 123456
    virtual-host: /user
gmall:
  jwt:
    pubKeyPath: E:\Git\gmallproject\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN    # cookie的名称
    userKey: user-key
alipay:
  app_id: 2016101600701035
  notify_url: http://9hgeyst0nt.52http.net/api/order/pay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: www.baid.com              #http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do   #支付宝网关
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDNDrH04U8+FxUaIUSOwUFBqu0ffU989sSBfDTQPggQVERHY0ZxL9BsFnortFZHPiTxBdk4/46/hOGAbqsIGIW7zl9/pqm0+ZpvdTPyWmaoo7afN/fVxFK7OIRFSeiGw/etCiA9OUWkjZqjI42nqxru4VaDyETV+1T14geaoKDfHmm7pLTcfsduYim57rxvCdafFmEMR+tXlSnC0sTDNRvVo7z70Akwo8QynATk1cOmt1pVLfbNOMRPLiVgS7bCwB/f1EEs1e71ANqu/feJ0VsDzocACj/EzlGwyjOvllMAzYp+yrDtD3IlemYwVVX7o8/tKeFNcwtjUpLpPByN/z3JAgMBAAECggEBAIAQp2+Kr5TVkaZKFKkbZQgAGivKdTRUYZGE4u8TbrHUDviOtdXGyOJYf2CANko0M5obzvhcEujlsnglpcdemVcbomT0z5RpNtxZVGINt4OnC00RBUWKYSjwORuU9xYDmdGGO3BBLo+AqI0ujS+kGyQJs6CGGQeS+hK+YYVewFnXZHR2DlAu20LvTFBOatCN58b1RNg1nirl91jWAvpdEjQsYVBxGVOiwaL1A8pUJIUkU9/+W2j53dEBxz+BfnfkNByRqtWN4yC9UyeJ6Kxc70+Q52Uwbif87fpsyzYAfyE3R6I+j6Vqeb/o6eqT+sGkCe5EIkeVTyAYYmFU5LvNQwkCgYEA6Mg+HYrifVZeKAMuQUYCXhs2s5WA8Md6HGlSAm3JpIlIQ3VAWKv+w/I9ZyTY/rokXMx2XMCJOqC/bEkSpvodfBnBajhnv9Li5y4At+VLhaacUg8v/SCp4zgAJ79rCImRJ9KfbYhXnlV4Qi7kSFKphgu7gCtf6e0/oVI6WbCMHBsCgYEA4YKKNlvZIzEONNQrOi59vikml+BdPIhzAKXWf4Hjub05TYnMb3p5XG7pgDHlbzDYCNpTVQDOd9AVrmMpUBJ5Alz5FkfzFvYulssGOpZXAE4L0psQ2rmWtydzKQeM8V1jrxTbYWP6sa9kkFaRLllQeroaGg7M+ZK/gS8vdO25Y+sCgYEAztw7jsc/9D/PFmGVNj4/ll86oiYGWnH5ysuxLCViHow8om3My7+0e26GMGWnS94guDKeMFiM2oPE+DaLk8UKdKDypzEOyYFfUC8qRkFGdrOTkLycWaYwMpIuWSQaupB9ZNUgBhc2PacYYkAHb1m9+jfs3L4u0tOZSwOmhNOF/ucCgYEAw17e8x07z3tOfYJbOPrSQY9ROj9NR4ZHbAZBARK9Akvnez+o9+O5hNUqQr/3sA82+uR7UadzOOX0ArMyNYbrg5qcyirndbsuvcGC0fsxwLfdEkb5oSUsZ90rrh42g12PYT3GmmeN56a2jz4QZYFHciwNNQohlw8GDpucl8bk2KUCgYBBNAE9YwQ1djMM1GZqeyhBSi/48azQPqGizZz3O+iKfzxj0KT/xqYWDZVxMgBAhBJBHwTwzLrqCYaSc49ej4mPe1Wo8dNUtlvZvMk+pnevOn0GbjpRhdNyJ2XzlUhXFeuD1Rz2T9S0YS2IRKuYx7GR692ZrQteFHrG87iYHuYf6Q==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArUWW8mN/8hZ+Q9ZKU+XJZ1y3MNHg/LGESL9/ae8FDwluA/FtntTqALSPAb3Riy1T1FmD60u8nNjkiFb5w35+uhiFLmLSpFVWQLrm7xWRhU3Irmkc3KG8933eFZf2lWk1jqQjJUa7RcgPvJ1g12Eij2603Gv7vSde8OQkcfYd9T/i5GYEPAby1ZdUYY2kSv09t7+OWyWwRZuVqMuhM3YDj81xjkeMmA1xQDT4U1zWhjJ/+2LA3LN6T4SKzRoVZ93Q/J9mWc49BbkT9369QFhQAdmXt9VpBk/tiwTl9gck0fQo+W03I5Y4pfVxjG2O3Y3SeoktczQZIWZbNHiBSuY5oQIDAQAB