server:
  port: 8090
spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.80.166
  rabbitmq:
    host: 192.168.80.166
    username: user
    password: 123456
    virtual-host: /user
gmall:
  jwt:
    pubKeyPath: E:\Git\gmallproject\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN # cookie的名称
    userKey: user-key