server:
  port: 8081
spring:
  application:
    name: pms-service

  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.166:3306/guli_pms
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.80.166
  rabbitmq:
    host: 192.168.80.166
    username: user
    password: 123456
    virtual-host: /user
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml

rabbitmq:
  exchange: GMALL-PMS-EXCHANGE

