server:
  port: 8082
spring:
  application:
    name: ums-service

  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.166:3306/guli_ums
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.80.166
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/ums/**/*.xml

sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appcode: d8795f7a8bcb4fe79f2683b59ac70c5b
